version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - "3001:3001"
    environment:
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_USER: user_crud
      DB_PASSWORD: root
      DB_NAME: db_crud
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
    stdin_open: true
    tty: true

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_crud
      MYSQL_USER: user_crud
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"  # Puerto expuesto en tu máquina host
